baseURL = "https://nautile.one/"
languageCode = "en-US"
paginate = 10
title = "Nautili Blog"
theme = "hugo-theme-stack"

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "zh-cn"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = true

[params]
  mainSections = ["post"]
  featuredImageField = "image"
  rssFullContent = true
  favicon = "images/favicon.png" # e.g.: favicon placed in `static/favicon.ico` of your site folder, then set this field to `/favicon.ico` (`/` is necessary)

  [params.footer]
    since = 2024
    customText = ""

  [params.dateFormat]
    published = "Jan 02, 2006"
    lastUpdated = "Jan 02, 2006"

  [params.sidebar]
    compact = true
    emoji = "🤔"
    subtitle = "Naut's Blog"
    
    [params.sidebar.avatar]
      enabled = true
      local = true
      src = "images/avatar.png"

  [params.article]
    math = false
    toc = true
    wordCount = true
    readingTime = true
    
    [params.article.license]
      enabled = true
      default = "Licensed under CC BY-NC-SA 4.0"

  [params.comments]
    enabled = true
    provider = "disqus"
    
    [params.comments.disqusjs]
      shortname = ""
      apiUrl = ""
      apiKey = ""
      admin = ""
      adminLabel = ""

    [params.comments.utterances]
      repo = ""
      issueTerm = "pathname"
      label = ""

    [params.comments.beaudar]
      repo = ""
      issueTerm = "pathname"
      label = ""
      theme = ""        

    [params.comments.remark42]
      host = ""
      site = ""
      locale = ""

    [params.comments.vssue]
      platform = ""
      owner = ""
      repo = ""
      clientId = ""
      clientSecret = ""
      autoCreateIssue = false

    [params.comments.waline]
      serverURL = ""
      lang = ""
      pageview = false
      emoji = ["https://unpkg.com/@waline/emojis@1.0.1/weibo"]
      requiredMeta = ["name", "email", "url"]
      
      [params.comments.waline.locale]
        admin = "Admin"
        placeholder = ""

    [params.comments.twikoo]
      envId = ""
      region = ""
      path = ""
      lang = ""

    [params.comments.cactus]
      defaultHomeserverUrl = "https://matrix.cactus.chat:8448"
      serverName = "cactus.chat"
      siteName = "" # You must insert a unique identifier here matching the one you registered (See https://cactus.chat/docs/getting-started/quick-start/#register-your-site)

    [params.comments.giscus]
      repo = ""
      repoID = ""
      category = ""
      categoryID = ""
      mapping = ""
      lightTheme = ""
      darkTheme = ""
      reactionsEnabled = 1
      emitMetadata = 0

    [params.comments.gitalk]
      owner = ""
      admin = ""
      repo = ""
      clientID = ""
      clientSecret = ""

    [params.comments.cusdis]
      host = ""
      id = ""

  [params.widgets]
    homepage = [
      { type = "search" },
      { type = "categories", params = { limit = 10 } },
      { type = "tag-cloud", params = { limit = 10 } },
      { type = "archives", params = { limit = 10 } }
      
    ]
    page = [
      { type = "toc" }
    ]

  [params.opengraph]
    [params.opengraph.twitter]
      site = "" # Your Twitter username
      card = "summary_large_image" # Available values: summary, summary_large_image

  [params.defaultImage]
    [params.defaultImage.opengraph]
      enabled = false
      local = false
      src = ""

  [params.colorScheme]
    toggle = true # Display toggle
    default = "auto" # Available values: auto, light, dark

  [params.imageProcessing]
    [params.imageProcessing.cover]
      enabled = true
    [params.imageProcessing.content]
      enabled = true

  [params.custom_css]
    ticket = "css/train_ticket.css"

[menu]

[[menu.main]]
  name = "Posts"
  weight = 30
  identifier = "archives"
  url = "/post/"
  [menu.main.params]
    icon = "article"  

[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 40
  identifier = "categories"
  [menu.main.params]
    icon = "category"  

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 50
  identifier = "tags"
  [menu.main.params]
    icon = "tag"  

[[menu.main]]
  name = "About Me"
  url = "/about/" 
  weight = 80
  identifier = "about"
  [menu.main.params]
    icon = "user"  

  [[menu.social]]
    identifier = "instagram"
    name = "Instagram"
    url = "https://www.instagram.com/allonautile/"
    [menu.social.params]
      icon = "brand-instagram"
      newTab = true
      
  [[menu.social]]
    identifier = "threads"
    name = "Threads"
    url = "https://www.threads.net/@allonautile"
    [menu.social.params]
      icon = "brand-threads"
      newTab = true

[related]
  includeNewer = true
  threshold = 60
  toLower = false
  [[related.indices]]
    name = "tags"
    weight = 100
  [[related.indices]]
    name = "categories"
    weight = 200

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # Set to true if you have HTML content inside Markdown
  [markup.tableOfContents]
    endLevel = 4
    ordered = true
    startLevel = 2
  [markup.highlight]
    noClasses = false
    codeFences = true
    guessSyntax = true
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    tabWidth = 4

[frontmatter]
  lastmod = [":fileModTime", "lastmod"]