baseURL = "https://blog.nautile.one/"
languageCode = "en-US"
paginate = 5
title = "Nautili Blog"
theme = "hugo-theme-stack"

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "zh-cn"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = true

[params]
  mainSections = ["post"]
  featuredImageField = "image"
  rssFullContent = true
  favicon = "" # e.g.: favicon placed in `static/favicon.ico` of your site folder, then set this field to `/favicon.ico` (`/` is necessary)

  [params.footer]
    since = 2020
    customText = ""

  [params.dateFormat]
    published = "Jan 02, 2006"
    lastUpdated = "Jan 02, 2006 15:04 MST"

  [params.sidebar]
    emoji = "🍥"
    subtitle = "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
    
    [params.sidebar.avatar]
      enabled = true
      local = true
      src = "img/avatar.png"

  [params.article]
    math = false
    toc = true
    readingTime = true
    
    [params.article.license]
      enabled = true
      default = "Licensed under CC BY-NC-SA 4.0"

  [params.comments]
    enabled = true
    provider = "disqus"
    
    [params.comments.disqusjs]
      shortname = ""
      apiUrl = ""
      apiKey = ""
      admin = ""
      adminLabel = ""

    [params.comments.utterances]
      repo = ""
      issueTerm = "pathname"
      label = ""

    [params.comments.beaudar]
      repo = ""
      issueTerm = "pathname"
      label = ""
      theme = ""        

    [params.comments.remark42]
      host = ""
      site = ""
      locale = ""

    [params.comments.vssue]
      platform = ""
      owner = ""
      repo = ""
      clientId = ""
      clientSecret = ""
      autoCreateIssue = false

    [params.comments.waline]
      serverURL = ""
      lang = ""
      pageview = false
      emoji = ["https://unpkg.com/@waline/emojis@1.0.1/weibo"]
      requiredMeta = ["name", "email", "url"]
      
      [params.comments.waline.locale]
        admin = "Admin"
        placeholder = ""

    [params.comments.twikoo]
      envId = ""
      region = ""
      path = ""
      lang = ""

    [params.comments.cactus]
      defaultHomeserverUrl = "https://matrix.cactus.chat:8448"
      serverName = "cactus.chat"
      siteName = "" # You must insert a unique identifier here matching the one you registered (See https://cactus.chat/docs/getting-started/quick-start/#register-your-site)

    [params.comments.giscus]
      repo = ""
      repoID = ""
      category = ""
      categoryID = ""
      mapping = ""
      lightTheme = ""
      darkTheme = ""
      reactionsEnabled = 1
      emitMetadata = 0

    [params.comments.gitalk]
      owner = ""
      admin = ""
      repo = ""
      clientID = ""
      clientSecret = ""

    [params.comments.cusdis]
      host = ""
      id = ""

  [params.widgets]
    homepage = [
      { type = "search" },
      { type = "archives", params = { limit = 5 } },
      { type = "categories", params = { limit = 10 } },
      { type = "tag-cloud", params = { limit = 10 } }
    ]
    page = [
      { type = "toc" }
    ]

  [params.opengraph]
    [params.opengraph.twitter]
      site = "" # Your Twitter username
      card = "summary_large_image" # Available values: summary, summary_large_image

  [params.defaultImage]
    [params.defaultImage.opengraph]
      enabled = false
      local = false
      src = ""

  [params.colorScheme]
    toggle = true # Display toggle
    default = "auto" # Available values: auto, light, dark

  [params.imageProcessing]
    [params.imageProcessing.cover]
      enabled = true
    [params.imageProcessing.content]
      enabled = true

[menu]
  [[menu.main]]
  [[menu.social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/CaiJimmy/hugo-theme-stack"
    [menu.social.params]
      icon = "brand-github"
  [[menu.social]]
    identifier = "twitter"
    name = "Twitter"
    url = "https://twitter.com"
    [menu.social.params]
      icon = "brand-twitter"

[related]
  includeNewer = true
  threshold = 60
  toLower = false
  [[related.indices]]
    name = "tags"
    weight = 100
  [[related.indices]]
    name = "categories"
    weight = 200

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # Set to true if you have HTML content inside Markdown
  [markup.tableOfContents]
    endLevel = 4
    ordered = true
    startLevel = 2
  [markup.highlight]
    noClasses = false
    codeFences = true
    guessSyntax = true
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    tabWidth = 4
